name: Django Verification CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    env:
      working-directory: ./pharmacies
          
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: ~/.cache/pip # This path is specific to Ubuntu
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: ${{ runner.os }}-pip-
          
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analisi statica (pylint)
      working-directory: ${{env.working-directory}}
      run: |
        pylint --rcfile=./.pylintrc ./shop --exit-zero
        
    - name: Code Refractoring (black)
      working-directory: ${{env.working-directory}}
      run: |
        black . --line-length 79
